server.port=8080
spring.application.name=pokemon-duel

# Evita erro de serialização de tipos Java 8+ com Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# Mostra logs de requisições HTTP
logging.level.org.springframework.web=INFO
